reboot:
  description: restart the device.
  fields:
    host: {description: IP address of device to restart., example: "192.168.0.1"}
init_device:
  description: run a command on  the device.
  fields:
    init_command: {description: command line, example: "add route XXXXXX"}
    host: {description: IP address of device to restart., example: "192.168.0.1"}
set_port_forward:
  description: set a port forward ruler on  the device.
  fields:
    ssid: {description: command line, example: "T1"}
    external_port: {description: port number., example: "5555"}
    internal_port: {description: port number., example: "5555"}
    target_host: {description: IP address of target., example: "192.168.0.1"}
run_command:
  description: run a command on  the device.
  fields:
    command_line: {description: command line, example: "add route XXXXXX"}
    host: {description: IP address of device to restart., example: "192.168.0.1"}